apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "monitoring.fullname" . }}
  namespace: {{ include "monitoring.smNamespace" . }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
        {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
        {{- include "policyreporter.selectorLabels" . | nindent 8 }}
  {{- with .Values.serviceMonitor.namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  endpoints:
  - port: http
    honorLabels: {{ .Values.serviceMonitor.honorLabels }}
    {{- if .Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- end }}
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    relabelings:
    - action: labeldrop
      regex: pod|service|container
    - targetLabel: instance
      replacement: policy-reporter
      action: replace
    {{- with .Values.serviceMonitor.relabelings }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 4 }}
    {{- end }}
